### ISSUE TITLE
Generic importers

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#10]
The folder structure now has different importer folders for each distinct data source. We should move them in a common "importer" folder. Also, we should separate concerns via a superclass or roles whenever possible.

Includes:

* Importing data
* Validation of command line options whenever relevant
* Abstract interfaces for connection to specific sources (database v. flat file)
* ...

**Comment by pieterdp** [comment]
Commit e5740a7d983648c0eedcf9ec681660e784a5fb59 has a (very) high-level overview of our plugin architecture. This could serve as a base for further documentation/refactoring.

**Comment by netsensei** [comment]
This issue has been fixed.
