### ISSUE TITLE
Documentation @ Wiki

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#18]
Suggestion to move the documentation from the docs/ folder in the source code to Github Wiki pages.

We could refer to the wiki from the main README through an absolute link.

**Comment by pieterdp** [comment]
The docs folder is used generate a Github Pages site for Datahub-Factory. (IMHO) it looks way better than a Wiki and is also more visible. We could also integrate it with a Github Pages site for the entire "thedatahub"-organisation, if we want.

**Comment by netsensei** [comment]
I think we need to re-consider documentation from a broader perspective. We should not be creating multiple disparate / independent mini-websites for each repository.

A central location to put all the documentation in would be a great because it lowers the bar for lower adoption. We don't want people to scour through loose pages & sites without much context.

A single, dedicated Github Pages website would be a great approach to do that, because it serves both concerns: central + better looking.

I've been putting off doing this until May per the planning we discussed earlier with Bert. Let's focus on wrapping up the codebase first, before starting to generate Jekyll websites.
