### ISSUE TITLE
Deprecate TMS module

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#39]
We have TMS supported in [Datahub-Factory-Arthub](https://github.com/thedatahub/Datahub-Factory-Arthub). The current TMS solution in Datahub-Factory banks on the idea that the TMS MS SQL database is [replicated](https://github.com/VlaamseKunstcollectie/tmssync) to MySQL since DBI doesn't allow remote connections to MS SQL which is the approach we use within Flemish Art Collection ecosystem.

Considering a more generic approach instead of the current case specific implementation?

**Comment by pieterdp** [comment]
If we can't connect from Perl to MS SQL, I think we should simply scrap the module. Otherwise, it should be converted to MS SQL and all KMSKA-specific code must be scrapped.

**Comment by netsensei** [comment]
Agreed. Let's scrap the TMS module from Datahub-Factory.

**Comment by netsensei** [comment]
Removed from the application.
