### ISSUE TITLE
Add: configuration file support

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#4]
Command now take a boatload of options and arguments which could / should be encapsulated in one or multiple configuration files.

Given that we leverage Catmandu, we should research whether or not we could take advantage of store configuration support.

**Comment by pieterdp** [comment]
We could do that, but as almost all options depend on which storage/importer pair you use, I think command line switches (as we use now) are better. For sensitive information we could use ENV. However, it's still worth a look.

**Comment by netsensei** [comment]
If we leverage configuration files, it would be easier to deploy this tool via Puppet or Ansible. 

We could create an Ansible template of the config file, and store app specific details in Ansibles' variables.yml file.  

Deploying a new pipeline between an new API and the Datahub entails nothing more then adding the necessary context specific variables to the Puppet role and deploy that to the server.  No need to log in directly into the server to make the necessary changes.

CLI options are still needed. But at this point we have to pass a ton of them to provide a specific context(OAuth, Importer, file, fix, etc.)

**Comment by netsensei** [comment]
Great. But we do need better documentation of the options you can put in a pipeline configuration and what they exactly do.  Perhaps inline documentation in the example pipeline.ini?

Also, what happens if I don't add required options in my file? Will there be a comprehensible error message? Or just a perl output on stderr? Does the code account for those cases too?

**Comment by pieterdp** [comment]
Documentation and modules have been updated. Error handling is still an issue.

**Comment by pieterdp** [comment]
Error handling is fixed.
