### ISSUE TITLE
JSON exporter shouldn't dump to STDOUT but to a flat file.

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#50]
The JSON exporter currently dumps the output to STDOUT. Within the functional scope of this project, that's not a valid data sink. Data should be exported persistently.  So, the JSON exporter should dump to a flat file by default.

The same is true for all exporters.

**Comment by pieterdp** [comment]
Wouldn't that inhibit piping commands? Or will STDOUT still be supported (e.g. by using '-' as a parameter).

**Comment by netsensei** [comment]
Correct. Gave it some thought. Dumping to STDOUT is perfectly fine in the *NIX philosophy. The only limitation is not being able to use the -v (verbose) flag because that prints to STDOUT a well.

This would only overcomplicate things.
