### ISSUE TITLE
Make Rackspace support optional

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub-Factory#8]
SQLite databases are stored on [Rackspace Cloudfiles](https://www.rackspace.com/cloud/files) by default so they can be reused when the import is rerun.

Even though it's a cheap service, it's not a free service. Rackspace support should be optional. Default behaviour should be to store sqlite databases in the `/tmp` folder. If they get purged, they should be regenerated.

Rackspace support should be there as an optional, configurable feature.

**Comment by pieterdp** [comment]
Databases are stored locally (in `/tmp`), but the original CSV-files we generate the sqlite databases from are stored on Cloudfiles. We could modify it so it accepts any locally/remotely stored CSV file however.

**Comment by pieterdp** [comment]
Closed in 61c0d582647a85caa0d4fa2c82da4b99d2a2630d
